#ifndef TESA_LOGGING_CONFIG_H
#define TESA_LOGGING_CONFIG_H

#ifndef TESA_LOGGING_DEFAULT_LEVEL
#define TESA_LOGGING_DEFAULT_LEVEL 2U
#endif

#ifndef TESA_LOGGING_ENABLE_VSCODE
#define TESA_LOGGING_ENABLE_VSCODE 1U
#endif

#ifndef TESA_LOGGING_ENABLE_COLORS
#if (1U == TESA_LOGGING_ENABLE_VSCODE)
#define TESA_LOGGING_ENABLE_COLORS 0U
#else
#define TESA_LOGGING_ENABLE_COLORS 1U
#endif
#endif

#ifndef TESA_LOGGING_ENABLE_TIMESTAMP
#define TESA_LOGGING_ENABLE_TIMESTAMP 1U
#endif

#ifndef TESA_LOGGING_TIMESTAMP_FORMAT
#define TESA_LOGGING_TIMESTAMP_FORMAT 1U
#endif
/* Timestamp format values:
 *   0U = TESA_LOG_TIMESTAMP_MS (milliseconds: [ms])
 *   1U = TESA_LOG_TIMESTAMP_FULL_DATETIME ([YYYY-MM-DD HH:MM:SS:XXX])
 *   2U = TESA_LOG_TIMESTAMP_TIME_ONLY ([HH:MM:SS:XXX])
 */

#ifndef TESA_LOGGING_CHANNEL_ID
#define TESA_LOGGING_CHANNEL_ID 0xFF00U
#endif

#ifndef TESA_LOGGING_EVENT_TYPE
#define TESA_LOGGING_EVENT_TYPE 0x0001U
#endif

#ifndef TESA_LOGGING_QUEUE_LENGTH
#define TESA_LOGGING_QUEUE_LENGTH 32U
#endif

#ifndef TESA_LOGGING_TASK_STACK_SIZE
#define TESA_LOGGING_TASK_STACK_SIZE 2048U
#endif

#ifndef TESA_LOGGING_TASK_PRIORITY
#define TESA_LOGGING_TASK_PRIORITY 5U
#endif

#ifndef TESA_LOGGING_TASK_NAME
#define TESA_LOGGING_TASK_NAME "LoggingTask"
#endif

#endif