#ifndef GYRO_TASK_CONFIG_H_
#define GYRO_TASK_CONFIG_H_

#define GYRO_TASK_STACK_SIZE (1024U)
#define GYRO_TASK_PRIORITY (2U)
#define GYRO_SEND_INTERVAL_MS (2000U)
#define GYRO_DATA_MIN (-1.0f)
#define GYRO_DATA_MAX (1.0f)

#endif
